// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategoryM = "categories"

// CategoryM mapped from table <categories>
type CategoryM struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`  // 名称
	ParentID  *int32    `gorm:"column:parent_id" json:"parent_id"` // 父级 id
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName CategoryM's table name
func (*CategoryM) TableName() string {
	return TableNameCategoryM
}
