// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceM = "resources"

// ResourceM mapped from table <resources>
type ResourceM struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`                       // 项目名
	Description string    `gorm:"column:description;not null" json:"description"`         // 中文说明，一般为项目 description
	Badge       string    `gorm:"column:badge;not null;default:default.png" json:"badge"` // 应用图标
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName ResourceM's table name
func (*ResourceM) TableName() string {
	return TableNameResourceM
}
